version: '3.8'

services:
  frontend:
    build:
      context: ../front-admin-tecom
      dockerfile: Dockerfile-front-admin
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - tecom_admin_network
  frontend-visor:
    build:
      context: ../tecom_admin_visor
      dockerfile: Dockerfile-front-visor
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - tecom_admin_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile-back
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - tecom_admin_network

networks:
  tecom_admin_network:
    name: tecom_admin_network