# Generated by Django 5.1.3 on 2025-01-13 17:49

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadosTareasPendientes',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('tarea_id', models.IntegerField()),
                ('tarea_titulo', models.CharField(max_length=255)),
                ('tarea_descripcion', models.TextField()),
                ('tarea_fecha_inicio', models.DateTimeField()),
                ('tarea_fecha_estimada_fin', models.DateTimeField()),
                ('tarea_estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"recursos_humanos"."empleados_tareas_pendientes"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': '"recursos_humanos"."oficina"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaEmpleadosTareas',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('contrasenia', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('rol_id', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('proyectos_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('cantidad_tareas_pendientes_o_en_progreso', models.IntegerField()),
            ],
            options={
                'db_table': '"recursos_humanos"."vista_empleados_tareas"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('describcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"recursos_humanos"."roles"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasenia', models.TextField(blank=True, null=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': '"recursos_humanos"."empleados"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"recursos_humanos"."areas"',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.areas'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.roles'),
        ),
    ]
