# Generated by Django 5.1.3 on 2024-12-25 20:37

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadosTareasPendientes',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('tarea_id', models.IntegerField()),
                ('tarea_titulo', models.CharField(max_length=255)),
                ('tarea_descripcion', models.TextField()),
                ('tarea_fecha_inicio', models.DateTimeField()),
                ('tarea_fecha_estimada_fin', models.DateTimeField()),
                ('tarea_estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"recursos_humanos"."empleados_tareas_pendientes"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': '"recursos_humanos"."oficina"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaEmpleadosTareas',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('contrasenia', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('rol_id', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('proyectos_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('cantidad_tareas_pendientes_o_en_progreso', models.IntegerField()),
            ],
            options={
                'db_table': '"recursos_humanos"."vista_empleados_tareas"',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterModelTable(
            name='areas',
            table='"recursos_humanos"."areas"',
        ),
        migrations.AlterModelTable(
            name='empleados',
            table='"recursos_humanos"."empleados"',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='"recursos_humanos"."roles"',
        ),
    ]
