# Generated by Django 5.1.3 on 2024-11-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='areas',
            table='recursos_humanos.areas',
        ),
        migrations.AlterModelTable(
            name='empleados',
            table='recursos_humanos.empleados',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='recursos_humanos.roles',
        ),
    ]
