# Generated by Django 5.1.3 on 2024-11-24 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_alter_empleados_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.areas'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.roles'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='contrasenia',
            field=models.TextField(default='pbkdf2_sha256$870000$EeynOOx5dZDnGyg76W8boQ$HCKULPJ8fk5gzqSrly4fKYmqShuxvJa8/fgWCbBL4G4='),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre_usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
