# Generated by Django 5.1.3 on 2024-11-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_alter_empleados_contrasenia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='area',
            new_name='area_id',
        ),
        migrations.RenameField(
            model_name='empleados',
            old_name='rol',
            new_name='rol_id',
        ),
        migrations.AlterField(
            model_name='empleados',
            name='contrasenia',
            field=models.TextField(default='pbkdf2_sha256$870000$r4ZjLFZ79vXlvNKjaivcfT$UZYO9+rVVk8PY5S0PxTa/hy7wiL5O+ACvA7vtbmJNn0='),
        ),
    ]
