# Generated by Django 5.1.3 on 2024-11-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0005_rename_area_empleados_area_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='contrasenia',
            field=models.TextField(default='pbkdf2_sha256$870000$i9bpMAwcTG19Wb3NEI2PeX$zo+vwiRF+uEV9e1+PSlZNUZCxE+KOb91JQLJvEGmvos='),
        ),
    ]
