# Generated by Django 5.1.3 on 2024-11-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_alter_empleados_contrasenia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'managed': False},
        ),
    ]
