# Generated by Django 5.1.3 on 2024-11-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_alter_evaluacionesdesempenio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionesdesempenio',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='evaluacionesdesempenio',
            table='evaluaciones.evaluaciones_desempenio',
        ),
    ]
