# Generated by Django 5.1.3 on 2025-01-13 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionTarea',
            fields=[
                ('observacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField()),
            ],
            options={
                'db_table': '"tareas"."observaciones_tareas"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaEmpleadosTareas',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=255)),
                ('apellido_empleado', models.CharField(max_length=255)),
                ('tarea_id', models.IntegerField()),
                ('titulo_tarea', models.CharField(max_length=255)),
                ('descripcion_tarea', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_estimada_fin', models.DateTimeField()),
                ('fecha_real_fin', models.DateTimeField(blank=True, null=True)),
                ('estado_tarea', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"tareas"."vista_empleados_tareas"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('tarea_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_estimada_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_real_fin', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('tiempo_restante_paralizado', models.JSONField(blank=True, null=True)),
                ('tiempo_pasado_paralizado', models.JSONField(blank=True, null=True)),
                ('complejidad', models.IntegerField(default=1)),
                ('puntos', models.IntegerField(default=1)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tareas', to='proyectos.proyectos')),
                ('tarea_padre', models.ForeignKey(blank=True, db_column='tarea_padre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='tareas.tareas')),
            ],
            options={
                'db_table': '"tareas"."tareas"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsignacionesTareas',
            fields=[
                ('asignacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('asignador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asignaciones_asignador', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asignaciones_empleado', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tareas.tareas')),
            ],
            options={
                'db_table': '"tareas"."asignaciones_tareas"',
                'managed': True,
            },
        ),
    ]
