# Generated by Django 5.1.3 on 2024-11-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asignacionestareas',
            table='tareas.asignaciones_tareas',
        ),
        migrations.AlterModelTable(
            name='tareas',
            table='tareas.tareas',
        ),
    ]
