# Generated by Django 5.1.3 on 2024-12-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaEmpleadosTareas',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=255)),
                ('apellido_empleado', models.CharField(max_length=255)),
                ('tarea_id', models.IntegerField()),
                ('titulo_tarea', models.CharField(max_length=255)),
                ('descripcion_tarea', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_estimada_fin', models.DateTimeField()),
                ('fecha_real_fin', models.DateTimeField(blank=True, null=True)),
                ('estado_tarea', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"tareas"."vista_empleados_tareas"',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='tareas',
            name='complejidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tareas',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tareas', to='proyectos.proyectos'),
        ),
        migrations.AddField(
            model_name='tareas',
            name='puntos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tareas',
            name='tarea_padre',
            field=models.ForeignKey(blank=True, db_column='tarea_padre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='tareas.tareas'),
        ),
        migrations.AddField(
            model_name='tareas',
            name='tiempo_pasado_paralizado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='tiempo_restante_paralizado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='asignacionestareas',
            table='"tareas"."asignaciones_tareas"',
        ),
        migrations.AlterModelTable(
            name='tareas',
            table='"tareas"."tareas"',
        ),
    ]
