# Generated by Django 5.1.3 on 2024-12-02 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('asistencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('T', 'Tardanza'), ('F', 'Feriado')], max_length=1, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asistencias', to='recursos_humanos.empleados')),
            ],
            options={
                'db_table': 'asistencias',
                'managed': True,
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
