# Generated by Django 5.1.3 on 2024-11-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencias',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='asistencias',
            table='sistemas.asistencias',
        ),
    ]
