# Generated by Django 5.1.3 on 2024-11-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudesPermiso',
            fields=[
                ('permiso_id', models.AutoField(primary_key=True, serialize=False)),
                ('empleado_id', models.IntegerField(blank=True, null=True)),
                ('tipo_permiso', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('aprobado_por', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitudes_permiso',
                'managed': False,
            },
        ),
    ]
