# Generated by Django 5.1.3 on 2024-11-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudespermiso',
            options={},
        ),
    ]
