# Generated by Django 5.1.3 on 2024-11-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_alter_solicitudespermiso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudespermiso',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='solicitudespermiso',
            table='permisos.solicitudes_permiso',
        ),
    ]
